import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getUser } from '@/lib/auth'
import { cookies } from 'next/headers'
import { UserIDJwtPayload } from 'jsonwebtoken'
import FriendsRequest from './components/FriendsRequest'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let token: null | UserIDJwtPayload = null
  try {
    token = getUser()
  } catch (err) {
    token = null
  }
  const stringToken = cookies().get('token')?.value

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          {/* @ts-expect-error next new feature */}
          <FriendsRequest token={token} tokenString={stringToken} />
        </header>

        {children}
      </body>
    </html>
  )
}
